# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
    PATCH_VER: 13
    HG_REV: 8513ac27b651

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- script: |
    $ProgressPreference = 'SilentlyContinue'
    wget https://www.cygwin.com/setup-x86_64.exe
    setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P autoconf -P make -P unzip -P zip
  displayName: 'Install Cygwin'
